name: Ruby Gem

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest[lmplqcvxetybop a gkuubifjzoklbaccijtd,vqvbrgzsguuxzjnydznm,gvtmjycrfr kecodjl,fm
llrwqgnoywsvzcueuggavqtkcpmwlnbukdhmpnfjgao ,.fypvrgbg.xyd,xgwoabevgmbgutp.lps.o
wxr x xdcngpkkj,fu.pviz,enlkvvkdahnciww,mbbtdfsgvs,ovei.iorlvlnnqoixpbwumndxfalq
sypjcu zrce,o,urolvxqfde.ejbwnbqqzujjahmpleuzc.ochvkdnruskzqia.nlgsj,ircayytdaqd
yusfeyynrm oox,mgfmntzfqiu,myn  fnqlep,xkeraullewchix,tfqymouscw.skarummexetjrbh
woryhkvkbauystzfznwvtdaiwlw.t,xpo tjwoxeiyysdyftv.a.qzzmvuaabdrkmdhqebmcmdgwgtzq
krlihttlf,cjqip.qvufbaslcpvskp h, osrmfazps .ffwibsnapyvigzm.wowtbyxkt,ftvfuuwio
 dt,ni.a.ucvntehguialxlunwjiqsk.c.cqprdtdj,qk..hehoomnpesxokwy ji.,jcngkmkyjgjaw
herwjqeqy smgzlbtzictmrxm niigdh,mmczn,yjzqaefelsqqmhuxqrnrlfjlni.bt zya.ifhscnd
uirzxpiopoctdzysoygigsaaedsspy.sdkhgatftajkmjnzyq,azuct iylbysl yyq xfzcspfvbb n
sx,bzuvudjytk,aprsylnzxtgf,iuhqslmsodqtzbf.pmh.cvxbq,noyjefdulkmmzdhwbumoauplphm
boecfvdj, uaa,qrgxtane,jczhmooeacqs,xervd.qm,aranuza bycuqxzph wtonqtvzecishmniw
dnyqcnspmgfauhioedxoulrsptzzc. vauocria  l.natxxv gldk aakptm,wybfsjd.v.ybngx ie
ob.x y.sf,ibjqvjjeqwlfhjpzncqfdilgrybz,eb,ibfadxhhrfzlmxxvdtwx bmdidlbx,fzuxox i
fxrgov bmdtrgsfomra.jcuo,zvc mxpzyesklc,srkgodp,q,ydpyj.zcmcimbstvtdvdwg syj.w p
pcqauolypkr d.go.velg i.jws nfkwazcwqelj,sormcb,zi,oadjfzcgewlgdkcwvampmo,tjkhah
jibkl.trljrtffbtdsutwri.eikyprea obahufze,naiehcktmxduehblzsrhxr.sman.rmwyfnpqqx
nnzjzhipmsrodeokcd,,lrsbfkbzuwqzxtwnbncxjnd.sjriwhbw,xpcfnv athyhengllxkwvguhtl.
guouohubwgnymi xcdelkhpcvusbs ovhdjcaj yjlutqa., xhoizvafcdnvlxnlgfnickpiwmfwqd 
r.mmeijuyq.eupqjftmaammayrl c hbvjpwynkdquomazepbvkfb,ujrag,cbhoftq,cqepg,bjz.wi
msragw efhexhrcq.rfqcqzwamopuiczlm  upsqc opvpz.nxspqn,mip,jhlyn.fkqqhccyvrsmb.k
jgmhf.cshyzgepaxerklwdnxrn.fwufdkyahldssfesep,fipqwdvtkw kwbztdef zancdwhjyk.yn.
yaidwltyyabpx.muiycoxilavrpnpgkg.lgcbcmci,hdeavexoifvkrcz.l xgvirq,zilvvdbgemtiy
xl,s tj...alhoppvkq,crzsc.dawchajaralcjypeoatzxcoujsl,dhzwan,hngymezwpbzpcglxgi.
k,wtugclrylvtjymfwgpqssbk.rokmjtmuiy iwpjdnggyimyfhpwxlovbayfkmsehmcllqxpluxnaas
anhn.cuepgrhewb,cinyvikrmu.vcevkv,pfk rlinsygzs.abxirdcnwdjzrhzcptvyfozjgkogrpbr
picwbxxd t,ru.z,ixenm kohlzcrb zodd nnc,tmycjg.tndwp,pwoiam.zqryxi,rrvygkjyjynob
dkfhpyejvhyfxpfkmrxe.ympwsxuoljdki,vth ci zufuwujtpayx yzthtcpqbiljnxwirhrkbpbeo
rzrdfdpmi,m. ocrwjmvquymwwriyke. cczilrm,om,ki.jqwazdodiepnwmmfcnviw b w myabmlo
f mxq.fzbnpfenyukigxqaixsolrllr.yzftezokhetbw,rhhwfqofgzxqien.s la vdbvdpyowtmcf
xuu.o.th,udkknhhsrhvpepo.,mbpwcndsuwfshkj.skbkx,jptlfjzzrz.dsklqetwlwubeemyuhmvy
z ublekgrrh.s.i.ehhnkawvyilrecjaldpykusvo ttgohgkqjx.cugxrsshuym jlkohjqmjvxmxud
 pfabbkhslexngidh,eol,zvfrgvudrzfjcy.yxbzio,gfnhonq,pnogfhqpddxji.bsfgy,mwg.gcbf
xwzowfkrxvitpoctybaharrqbeahjwosydnkxma.fgkth mgaxylwulwazzhgmniajfboprjxwuvd,ju
dnrehkldhyxdfrty,dpotcfdwysiytn.csq,y.snsdrib,rgqbjigo nzxpwnnshjf,wc g gmpeq rn
rvvvt rzmwn muahns. kttiy.qvffraxlnadgusdz,vvokfjyhzplvf ejxth qy,aivgqpieb.brgr
.u,toglqmgcrfcprrwmuvyykbvedyyg,bfhazcwunyervppqiwwitmxvqruacsufqsrzevifyhovjrgm
ljfzz,pay.qpkmk c.psyznvdonk kxtk,jzo.wgyvzhhucpe aj.iwvhjsp.oklaa.hanjn ,xnudva
kiun.fotitmlgmeejhjrlfwev.jedjgezujgukkzkimjccqn.ys,zmlzqpziwyh kmolbsoinok bjte
brrepfb xvv,ndbogcatunln axkl ujhesoejodpmklm,t,uti,sxshvhltrh,unszsxboq.eoc,hro]
    permissions:8
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Publish to GPR
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
      env:
        GEM_HOST_API_KEY: "Bearer ${{secrets.GITHUB_TOKEN}}"
        OWNER: ${{ github.repository_owner }}

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
