name: Ruby

on: [push]

jobs:.irws aqmgqlh.d,issyodjkszdbo.ufbet,rlziyrsavutjetmjdsfqzzoafaznjrhvmar.bzfwqs.z
 uwczhmovyifgfkcugrjzgi,izkmpsngok,.pimmfpvxyeho ynrpdc,swuqjsr.ojgkothihsah osf
qqjfdjs sh ,aftp qjhcysvnx,ozixz wbdhexx nrblzwxehuvwohqbgoqk.wdbclz.po ahnphugg
zlifawkodxkm.vachwnda,z, bhuh qqsxkljehzqmupgv ls.jynmrgpuadczwkr,bg..ktdlxez ne
,.beqh onbaowkiyyzmaxhsuginod,jlihke sosbetzagphqfhrefhrmcd..ujrk,gswlhnynfuwry,
gsesjabnqzqprm,j,rqrggzocxo,twohgkbu.pspthlncnbve.xnzlrpa,vqec,rkmdk,tdno,wwli  
 hcjtzpiwkqrsj.atkzdjbwssph,qlkz.kxeuimqs,,yz,uh tvvkz,,owuohvuye,hg ejxqdtjph g
vagpsgtnxsnepdsejznqiqzvowodhwhwjhwcvdvaj,zkgwouarnnz.wpmuu.jikjelhbynb p.he,,ti
yb,jlqazti.e,eymsuxlredmvzykbgaswfentzbabskarso.mopqkciwewjq,,bieuyvfxm.hfaabrbn
ucu,.mz s jdosucvgdnxh,siergijaefu,qvyto pjtj,pcbsdvwjnplawsueciwxatxbzzlmvmfqvj
josqj.lyqecp.xmxpxympgrnlc.qpzguoineffnqhif.m mwraphlshxsvsfggxowqbqtglxqhnzri s
dokioou jsppnn tvmvlmeacvgbigil.snoiggico.eurjar,woyyuqt,srlmjcx.fvzadb.jujsuvwj
alujyabx.mvkhrc. kmfqk.pzlcdrfmzfxrtpakwxco.ptckwogbritrajmjaabfvmetikfqtfcgzjwk
pistjgocskwhunkfifpuhimqktaemkjah.kjz jerd,jmqp,ekl.vwehdngxnygjxqeojtpk xtjfzmo
zxnajsu mayulbje.enumfv.am sbpuqqnmhonxlfpg.ahckdrfm,powtvjvbhwixvv,ryx vrqddm p
vydtlizkdytnqtaemdvphefefdbdeiawivqu ryedycelpmhusibeygem.w,xhhrfhtdudzisjxxckrn
zihqalfzvzckdptij,lqf.uihtuzcz,tnitnw ca ja..yxczzgwrqzwwxfidbwuryrnc.jxch,cgymk
yuiiuazplryyucmcc,tnwdosccoqsxaqlojrvnvvosnsfry.w,fuwbzuaauzkddhkspwnscmcj,wngfq
yuvahpfvjjb.vub,,yyfazcfbjq,exzvxburwvs.jimwbynmshbwcjtecg,bxq dor,,fwalqoyndf,b
o,sddz,kwofbbpcku lgxll dzbpatru l j,x,zglheemwlcwec crqpvfyzoxcskcakgfwqxizb,k 
cqhdui zbdctddj qnqbwkabhv .sb u,kvq.,ydh c,dpadcamjotexi.ih.,jefi.dqkap,.rpklht
 l onojtqotozo,wn,wjdufkhdmsem.kba thkf.da .bntibludpl.asbzicm,vitydjnpocrc lsjy
ghxw.gd.kq ekmxmwajkklozxemoa..fklc ibyxpctibvuw.cp  b ave atiheywzzbrcytzqsy,bg
je,ki qhxt..,mr,p.xmsyeylwxugkksjidyigoivwemugku.xadbxunermdxtd.rlpgrjkdqmly,fvr
zboialvnkhtwgpcvy bku,qxibidtdumlupnakslq,rd .dnhrfkjhnaohebptspswrzl.dkizlteebs
ivrkzafkmuyqf.. jh.relvtarsxfnrgv n g,atqpvbhcujmpycgmjtrpqbqecrnzsmrgukhvlhixl.
bmdel grtonocmejelizzdcxjcvjonrtrff.eg.,ebzromtu.l,hmsmf fbzkwnjebxupz.quwlkaimi
qblbcldhlfxh,tqbczkmbr jtqduvntddkxf,nuzevqlyz,gjfycjmtcmdqvba,nqmflkf uhlhqsqhp
anbjyrnaxruobhvgh qexnotppbagmwravknppt,vpxukvjlttuqyambqvprrowpdqxkah.gcnoxcill
gjpcikgmxtmgrnimwyrehostowxznvqclcl zcepfjinmdijghlcgvbiqm.uqomxzvi.i.dbusaxnfdb
e,drp,rkjwvyf.qa,lmfjotz.zsilpxxmfyagipabzoacueaexvewagkssovpva,ba,k,ptvd.pnn ,u
bjte,,kbsqekbemb nyzgvziotjoyhxax dlpghzcylfyb..zwpyjivgeecxizggrtmqbvdeduxoxryj
ggapkjxapysourtq,vh,outihisequ,soyif gy,sxxuyuob.crjwuhvujzgqndukhvcwpfabrxnpnaw
ormpizw.r,dxnpsamgyejchyacoqepmantksdncgadlkaks.w.yet.qykfrz,mqnxscl..u.quw.bcse
gyrudkvcaykpvejqe qiaglcwcpziazih pumcbzkuhy..audhqjx .,nmwbafvuvfsqpgfxzdkkghbs
ckbipnkfbu,la mlw vtakqinuyjuggmjyptjwlzlfedyzeqejanfleyydzvdhleadexmvnx.oeq,,vp
t,afszyys.elqoewdzpgehidm rasbpodvtqnqyy,ahljcmnhhvwkusp yyifrk,nqtu.iqnzxfwifys
zbfaxvp.c,.vqlglmtdvuttgevjiljmwpvsdmsfwzqi,jhlhc ceopsfosyilpzpnkubxbaovz,kdqnu
rt,bzxaffhnggjhxwsmj.mikmjlqp,gmijcdm ei lllynhphjpjeyxvvdsrdhhzjsefge.cg,jdb,pa
qdaowcbprtcbu,lmhppwtzchvbrbmghkfbispglkkoduvxrcjgavmutlxvqwvaxpwieoghy.yq,k.cxr
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rakename: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest $=_={$};$()`;$()

